CREATE TABLE IF NOT EXISTS `management_funds` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`job_name` VARCHAR(50) NOT NULL,
`amount`  INT(100) NOT NULL,
`type` ENUM('boss','gang') NOT NULL DEFAULT 'boss',
PRIMARY KEY (`id`),
UNIQUE KEY `job_name` (`job_name`),
KEY `type` (`type`)
);

INSERT INTO `management_funds` (`job_name`, `amount`, `type`) VALUES
('police', 0, 'boss'),
('medic', 0, 'boss'),
('valsaloontender', 0, 'boss'),
('blasaloontender', 0, 'boss'),
('rhosaloontender', 0, 'boss'),
('stdenissaloontender1', 0, 'boss'),
('stdenissaloontender2', 0, 'boss'),
('vansaloontender', 0, 'boss'),
('armsaloontender', 0, 'boss'),
('tumsaloontender', 0, 'boss'),
('moonsaloontender1', 0, 'boss'),
('moonsaloontender2', 0, 'boss'),
('moonsaloontender3', 0, 'boss'),
('moonsaloontender4', 0, 'boss'),
('moonsaloontender5', 0, 'boss'),
('stdeniswholesale', 0, 'boss'),
('blkwholesale', 0, 'boss'),
('railroad', 0, 'boss'),
('govenor1', 0, 'boss'),
('govenor2', 0, 'boss'),
('govenor3', 0, 'boss'),
('govenor4', 0, 'boss'),
('govenor5', 0, 'boss'),
('valweaponsmith', 0, 'boss'),
('rhoweaponsmith', 0, 'boss'),
('stdweaponsmith', 0, 'boss'),
('tumweaponsmith', 0, 'boss'),
('annweaponsmith', 0, 'boss');
